// AUTO-GENERATED by build.py - do not edit by hand.
const SCHEDULE_DATA = {
  "meta": {
    "title": "ScheduleFreeTime - Free Time Scoreboard (Aug-Oct 2026)",
    "timezone": "America/Los_Angeles (PT; Aug-Oct 2026 = PDT, UTC-7)",
    "range": {
      "start": "2026-08-01",
      "end": "2026-10-31"
    },
    "durationsMin": {
      "MLB": 158,
      "NFL": 192,
      "Stanford": 200,
      "Cal": 200,
      "MLS": 120
    },
    "sources": {
      "MLB": {
        "name": "MLB Stats API (statsapi.mlb.com) + mlb.com Giants schedule",
        "url": "https://www.mlb.com/giants/schedule"
      },
      "NFL": {
        "name": "49ers.com official schedule (preseason per 49ers.com news release)",
        "url": "https://www.49ers.com/schedule"
      },
      "Stanford": {
        "name": "Stanford Athletics official football schedule (gostanford.com)",
        "url": "https://gostanford.com/sports/football/schedule"
      },
      "Cal": {
        "name": "California Athletics official football schedule (calbears.com)",
        "url": "https://calbears.com/sports/football/schedule"
      },
      "MLS": {
        "name": "San Jose Earthquakes official 2026 schedule announcement (sjearthquakes.com)",
        "url": "https://www.sjearthquakes.com/news/news-earthquakes-announce-2026-major-league-soccer-schedule"
      }
    },
    "flags": [
      "INTERPRETATION: 'no MLB games on' was interpreted as the San Francisco Giants (Bay Area MLB team) regular-season games only. If you meant ALL 30 MLB teams, or the Athletics, the scope is much larger (~15 MLB games/day). Flagged for your review.",
      "MLB POSTSEASON EXCLUDED: The 2026 MLB regular season ends Sun Sep 27, 2026 (official MLB). Postseason (Wild Card Sep 29, LDS, LCS, World Series through ~Oct 31) is NOT included because the Giants (standings: 4th NL West) are not in playoff contention; if you watch all postseason MLB, October would have many additional busy days.",
      "TBD GAME TIMES (free-time for these days is best-effort / excluded until confirmed): Stanford Oct 3 & Oct 31; Cal Oct 10, 17, 24, 31; Earthquakes Oct 31.",
      "AWAY-GAME TIMES: Cal & Stanford away games are shown in PT per the schools' official schedule sites (school-local time). Verified against ESPN (ET): e.g., Stanford @ Duke 4:00 PM ET = 1:00 PM PT.",
      "EARTHQUAKES TIMES are PT per the official sjearthquakes.com announcement; ESPN lists the same games in ET (e.g., 7:30 PM PT = 10:30 PM ET) - consistent.",
      "49ERS PRESEASON times are from the official 49ers.com news release (the schedule page lists them as FINAL without times). Regular-season times are from 49ers.com/schedule.",
      "DURATIONS are research-based ESTIMATES, not exact per-game: MLB 158 min (2025 avg 2:38), NFL 192 min (2025 avg 3:12), CFB 200 min (2025 avg ~3:24), MLS 120 min. Football durations include halftime (NFL 12 min, CFB 20 min).",
      "The prior schedules.md in this repo was largely hallucinated (wrong 49ers opener time, wrong Cal ET/PT conversions, fabricated MLB matchups, missing Earthquakes Aug 1). It has been fully replaced."
    ],
    "generated": "2026-08-28"
  },
  "games": [
    {
      "date": "2026-08-01",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes at FC Cincinnati",
      "homeAway": "away",
      "startPT": "4:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-08-01",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at San Diego Padres",
      "homeAway": "away",
      "startPT": "5:40 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-02",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at San Diego Padres",
      "homeAway": "away",
      "startPT": "1:10 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-03",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Texas Rangers",
      "homeAway": "away",
      "startPT": "5:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-04",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Texas Rangers",
      "homeAway": "away",
      "startPT": "5:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-05",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Texas Rangers",
      "homeAway": "away",
      "startPT": "11:35 AM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-07",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Detroit Tigers",
      "homeAway": "home",
      "startPT": "7:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-08",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Detroit Tigers",
      "homeAway": "home",
      "startPT": "4:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-09",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Detroit Tigers",
      "homeAway": "home",
      "startPT": "1:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-10",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Houston Astros",
      "homeAway": "home",
      "startPT": "6:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-11",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Houston Astros",
      "homeAway": "home",
      "startPT": "6:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-12",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Houston Astros",
      "homeAway": "home",
      "startPT": "12:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-13",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers vs Tennessee Titans (Preseason Wk1)",
      "homeAway": "home",
      "startPT": "6:00 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-08-14",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Colorado Rockies",
      "homeAway": "home",
      "startPT": "7:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-15",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Colorado Rockies",
      "homeAway": "home",
      "startPT": "1:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-15",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes vs St. Louis CITY SC",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-08-16",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Colorado Rockies",
      "homeAway": "home",
      "startPT": "1:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-18",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Cleveland Guardians",
      "homeAway": "away",
      "startPT": "3:40 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-19",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Cleveland Guardians",
      "homeAway": "away",
      "startPT": "3:40 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-19",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes at LA Galaxy",
      "homeAway": "away",
      "startPT": "7:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-08-20",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Cleveland Guardians",
      "homeAway": "away",
      "startPT": "10:10 AM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-20",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers at Los Angeles Chargers (Preseason Wk2)",
      "homeAway": "away",
      "startPT": "7:00 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-08-21",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Boston Red Sox",
      "homeAway": "away",
      "startPT": "4:10 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-22",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Boston Red Sox",
      "homeAway": "away",
      "startPT": "4:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-22",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes vs Minnesota United FC",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-08-23",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Boston Red Sox",
      "homeAway": "away",
      "startPT": "12:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-24",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Cincinnati Reds",
      "homeAway": "home",
      "startPT": "6:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-25",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Cincinnati Reds",
      "homeAway": "home",
      "startPT": "6:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-26",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Cincinnati Reds",
      "homeAway": "home",
      "startPT": "12:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-27",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers vs Las Vegas Raiders (Preseason Wk3)",
      "homeAway": "home",
      "startPT": "5:00 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-08-27",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Arizona Diamondbacks",
      "homeAway": "home",
      "startPT": "6:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-28",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Arizona Diamondbacks",
      "homeAway": "home",
      "startPT": "7:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-29",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Arizona Diamondbacks (DH1)",
      "homeAway": "home",
      "startPT": "1:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-29",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford vs Hawai'i Rainbow Warriors",
      "homeAway": "home",
      "startPT": "4:00 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-08-29",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes at Houston Dynamo FC",
      "homeAway": "away",
      "startPT": "5:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-08-29",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Arizona Diamondbacks (DH2)",
      "homeAway": "home",
      "startPT": "7:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-08-31",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Atlanta Braves",
      "homeAway": "away",
      "startPT": "3:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-01",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Pittsburgh Pirates",
      "homeAway": "away",
      "startPT": "3:40 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-02",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Pittsburgh Pirates",
      "homeAway": "away",
      "startPT": "3:40 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-03",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Pittsburgh Pirates",
      "homeAway": "away",
      "startPT": "9:35 AM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-04",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at New York Mets",
      "homeAway": "away",
      "startPT": "4:10 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-04",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford vs Miami Hurricanes",
      "homeAway": "home",
      "startPT": "6:00 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-09-05",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at New York Mets",
      "homeAway": "away",
      "startPT": "1:10 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-05",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes at Austin FC",
      "homeAway": "away",
      "startPT": "5:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-09-05",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal vs UCLA Bruins",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-09-06",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at New York Mets",
      "homeAway": "away",
      "startPT": "10:40 AM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-07",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs St. Louis Cardinals",
      "homeAway": "home",
      "startPT": "5:10 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-08",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs St. Louis Cardinals",
      "homeAway": "home",
      "startPT": "6:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-09",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs St. Louis Cardinals",
      "homeAway": "home",
      "startPT": "12:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-09",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes at San Diego FC",
      "homeAway": "away",
      "startPT": "7:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-09-10",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers at Los Angeles Rams (Wk1, Melbourne AUS)",
      "homeAway": "away",
      "startPT": "5:35 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-09-11",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs San Diego Padres",
      "homeAway": "home",
      "startPT": "7:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-12",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal at Syracuse Orange",
      "homeAway": "away",
      "startPT": "12:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-09-12",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs San Diego Padres",
      "homeAway": "home",
      "startPT": "1:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-12",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes vs Houston Dynamo FC",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-09-13",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs San Diego Padres",
      "homeAway": "home",
      "startPT": "4:20 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-14",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at St. Louis Cardinals",
      "homeAway": "away",
      "startPT": "4:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-15",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at St. Louis Cardinals",
      "homeAway": "away",
      "startPT": "4:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-16",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at St. Louis Cardinals",
      "homeAway": "away",
      "startPT": "10:15 AM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-18",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Los Angeles Dodgers",
      "homeAway": "away",
      "startPT": "7:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-19",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal vs Wagner Seahawks",
      "homeAway": "home",
      "startPT": "12:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-09-19",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford at Duke Blue Devils",
      "homeAway": "away",
      "startPT": "1:00 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-09-19",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes vs LAFC",
      "homeAway": "home",
      "startPT": "4:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-09-19",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Los Angeles Dodgers",
      "homeAway": "away",
      "startPT": "6:10 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-20",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants at Los Angeles Dodgers",
      "homeAway": "away",
      "startPT": "1:10 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-20",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers vs Miami Dolphins (Wk2)",
      "homeAway": "home",
      "startPT": "1:25 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-09-21",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Minnesota Twins",
      "homeAway": "home",
      "startPT": "6:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-22",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Minnesota Twins",
      "homeAway": "home",
      "startPT": "6:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-23",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Minnesota Twins",
      "homeAway": "home",
      "startPT": "12:45 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-25",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Los Angeles Dodgers",
      "homeAway": "home",
      "startPT": "7:15 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-25",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal vs Clemson Tigers",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-09-26",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Los Angeles Dodgers",
      "homeAway": "home",
      "startPT": "1:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-26",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford vs Georgia Tech Yellow Jackets",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-09-26",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes vs Portland Timbers",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-09-27",
      "league": "MLB",
      "team": "Giants",
      "matchup": "Giants vs Los Angeles Dodgers",
      "homeAway": "home",
      "startPT": "12:05 PM",
      "durationMin": 158,
      "tbd": false
    },
    {
      "date": "2026-09-27",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers vs Arizona Cardinals (Wk3)",
      "homeAway": "home",
      "startPT": "1:05 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-10-03",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford at Wake Forest Demon Deacons",
      "homeAway": "away",
      "startPT": null,
      "durationMin": 200,
      "tbd": true
    },
    {
      "date": "2026-10-03",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal at UNLV Rebels",
      "homeAway": "away",
      "startPT": "12:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-10-04",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers vs Denver Broncos (Wk4)",
      "homeAway": "home",
      "startPT": "1:25 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-10-10",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal vs Virginia Tech Hokies",
      "homeAway": "home",
      "startPT": null,
      "durationMin": 200,
      "tbd": true
    },
    {
      "date": "2026-10-10",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford at Notre Dame Fighting Irish",
      "homeAway": "away",
      "startPT": "12:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-10-10",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes at Colorado Rapids",
      "homeAway": "away",
      "startPT": "6:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-10-11",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers at Seattle Seahawks (Wk5)",
      "homeAway": "away",
      "startPT": "1:25 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-10-14",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes at Real Salt Lake",
      "homeAway": "away",
      "startPT": "6:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-10-17",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal vs Wake Forest Demon Deacons",
      "homeAway": "home",
      "startPT": null,
      "durationMin": 200,
      "tbd": true
    },
    {
      "date": "2026-10-17",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford vs Elon Phoenix",
      "homeAway": "home",
      "startPT": "4:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-10-17",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes vs Nashville SC",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-10-19",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers vs Washington Commanders (Wk6, MNF)",
      "homeAway": "home",
      "startPT": "5:15 PM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-10-23",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford vs NC State Wolfpack",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 200,
      "tbd": false
    },
    {
      "date": "2026-10-24",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal at SMU Mustangs",
      "homeAway": "away",
      "startPT": null,
      "durationMin": 200,
      "tbd": true
    },
    {
      "date": "2026-10-24",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes at FC Dallas",
      "homeAway": "away",
      "startPT": "5:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-10-25",
      "league": "NFL",
      "team": "49ers",
      "matchup": "49ers at Atlanta Falcons (Wk7)",
      "homeAway": "away",
      "startPT": "10:00 AM",
      "durationMin": 192,
      "tbd": false
    },
    {
      "date": "2026-10-28",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes vs Colorado Rapids",
      "homeAway": "home",
      "startPT": "7:30 PM",
      "durationMin": 120,
      "tbd": false
    },
    {
      "date": "2026-10-31",
      "league": "Stanford",
      "team": "Stanford",
      "matchup": "Stanford at Louisville Cardinals",
      "homeAway": "away",
      "startPT": null,
      "durationMin": 200,
      "tbd": true
    },
    {
      "date": "2026-10-31",
      "league": "Cal",
      "team": "Cal",
      "matchup": "Cal at NC State Wolfpack",
      "homeAway": "away",
      "startPT": null,
      "durationMin": 200,
      "tbd": true
    },
    {
      "date": "2026-10-31",
      "league": "MLS",
      "team": "Earthquakes",
      "matchup": "Earthquakes vs Real Salt Lake",
      "homeAway": "home",
      "startPT": null,
      "durationMin": 120,
      "tbd": true
    }
  ]
};
